stages:
  validate_and_save_data:
    cmd: python src/load_data.py --config=params.yaml
    deps:
    - src/load_data.py
    - src/functions.py
    - data_validation/validate_data.py
    - logger/myLogger.py
    - data/external/
    outs:
    - data/raw/master_dataset.csv

  preprocess_and_split_data:
    cmd: python src/preprocess_data.py --config=params.yaml
    deps:
    - src/preprocess_data.py
    - data/raw/master_dataset.csv
    - logger/myLogger.py
    - src/functions.py
    - src/preprocess_functions.py
    outs:
    - saved_artifacts/std_scaler.pkl
    - saved_artifacts/label_encoder.pkl
    - data/processed/train_dataset.csv
    - data/processed/test_dataset.csv

  train_and_evaluate:
    cmd: python src/train_and_eval.py --config=params.yaml
    deps:
    - src/train_and_eval.py
    - logger/myLogger.py
    - src/functions.py
    - data/processed/train_dataset.csv
    - data/processed/test_dataset.csv
    params:
    - estimators.RandomForestClassifier.params.n_estimators
    - estimators.RandomForestClassifier.params.criterion
    metrics:
    - reports/params.json:
        cache: false
    - reports/scores.json:
        cache: false
    outs:
    - saved_models/rfc_model.pkl

