base:
  project: activity_recognition_project
  target_col: label
  random_state: 45

data_source:
  source_dir: data/external

data_paths:
  raw_dataset_csv: data/raw/master_dataset.csv

preprocess:
  cols_to_remove: ["# Columns: time"]


split_data:
  train_path: data/processed/train_dataset.csv
  test_path: data/processed/test_dataset.csv
  test_size: 0.2

algorithm_name: 
  Random Forest Classifier

estimators:
  RandomForestClassifier:
    params:
      n_estimators: 75
      criterion: entropy

artifact_dir: saved_artifacts
model_dir: saved_models

reports:
  params: reports/params.json
  scores: reports/scores.json

webapp_model: saved_models/rfc_model.pkl
scaler: saved_artifacts/std_scaler.pkl
label_encoder: saved_artifacts/label_encoder.pkl